// ============================================
// 🚀 Две Дилеммы — Original by Nebo
// Created with ❤️ | Version 2.0
// ============================================
(function(){var _0xnebo=atob('Q3JlYXRlZCBieSBOZWJvIC0g0JLRgdC1INC/0YDQsNCy0LAg0LfQsNGJ0LjRidC10L3Riw==');if(window.location.hostname!=='localhost'){console.log(atob('0J7RgNC40LPQuNC90LDQuyBieSBOZWJv'))}})();

// ================= 1. ДАННЫЕ =================
const dilemmasRU = [
    { id: 1, question: "На рельсах собака и кошка. Кого вы спасёте?", optionA: "Собаку", optionB: "Кошку", category: "relationships" },
    { id: 2, question: "Уметь летать или становиться невидимым?", optionA: "Летать", optionB: "Невидимость", category: "games" },
    { id: 3, question: "Жить в мире без музыки или без кино?", optionA: "Без музыки", optionB: "Без кино", category: "movies" },
    { id: 4, question: "Бесконечная еда или бесконечные путешествия?", optionA: "Еда", optionB: "Путешествия", category: "food" },
    { id: 5, question: "Всегда говорить только правду или всегда врать?", optionA: "Правда", optionB: "Ложь", category: "relationships" },
    { id: 6, question: "Сразиться с 100 утками размером с лошадь или 1 лошадью размером с утку?", optionA: "100 уток", optionB: "1 лошадь", category: "games" },
    { id: 7, question: "Пицца с ананасами — это вкусно?", optionA: "Да! 👍", optionB: "Нет! 👎", category: "food" },
    { id: 8, question: "Телепортация или чтение мыслей?", optionA: "Телепортация", optionB: "Чтение мыслей", category: "games" },
    { id: 9, question: "Смотреть фильм по книге или читать книгу до фильма?", optionA: "Сначала фильм", optionB: "Сначала книга", category: "movies" },
    { id: 10, question: "Жить в деревне или в мегаполисе?", optionA: "Деревня", optionB: "Мегаполис", category: "relationships" },
    { id: 11, question: "Быть богатым и одиноким или бедным, но любимым?", optionA: "Богатым", optionB: "Любимым", category: "relationships" },
    { id: 12, question: "Кофе или чай?", optionA: "Кофе ☕", optionB: "Чай 🍵", category: "food" },
    { id: 13, question: "Утро или вечер?", optionA: "Утро 🌅", optionB: "Вечер 🌆", category: "relationships" },
    { id: 14, question: "Писать ручкой или печатать на клавиатуре?", optionA: "Ручка", optionB: "Клавиатура", category: "other" },
    { id: 15, question: "Жить без интернета или без еды неделю?", optionA: "Без интернета", optionB: "Без еды", category: "other" },
    { id: 16, question: "Дракон или феникс?", optionA: "Дракон 🐉", optionB: "Феникс 🔥", category: "games" },
    { id: 17, question: "Minecraft или Roblox?", optionA: "Minecraft", optionB: "Roblox", category: "games" },
    { id: 18, question: "Зима или лето?", optionA: "Зима ❄️", optionB: "Лето ☀️", category: "other" },
    { id: 19, question: "Пицца или суши?", optionA: "Пицца 🍕", optionB: "Суши 🍣", category: "food" },
    { id: 20, question: "Быть супергероем или суперзлодеем?", optionA: "Герой", optionB: "Злодей", category: "games" },
    { id: 21, question: "Жить в прошлом или в будущем?", optionA: "Прошлое", optionB: "Будущее", category: "other" },
    { id: 22, question: "Собака или кошка?", optionA: "Собака 🐕", optionB: "Кошка 🐈", category: "relationships" },
    { id: 23, question: "iPhone или Android?", optionA: "iPhone 📱", optionB: "Android 🤖", category: "other" },
    { id: 24, question: "Горы или море?", optionA: "Горы ⛰️", optionB: "Море 🌊", category: "other" },
    { id: 25, question: "Книга или фильм?", optionA: "Книга 📚", optionB: "Фильм 🎬", category: "movies" },
    { id: 26, question: "Сладкое или солёное?", optionA: "Сладкое 🍰", optionB: "Солёное 🍟", category: "food" },
    { id: 27, question: "Быть невидимым или летать?", optionA: "Невидимость", optionB: "Полёт", category: "games" },
    { id: 28, question: "Смотреть сериал залпом или по серии в день?", optionA: "Залпом", optionB: "По серии", category: "movies" },
    { id: 29, question: "Работать в офисе или удалённо?", optionA: "Офис", optionB: "Удалёнка", category: "relationships" },
    { id: 30, question: "Иметь машину времени или портал в другие миры?", optionA: "Машина времени", optionB: "Портал", category: "games" },
    { id: 31, question: "Плавать или летать?", optionA: "Плавать 🏊", optionB: "Летать ✈️", category: "other" },
    { id: 32, question: "Быть умным или красивым?", optionA: "Умным", optionB: "Красивым", category: "relationships" },
    { id: 33, question: "Жить вечно или умереть молодым, но ярко?", optionA: "Вечно", optionB: "Ярко", category: "other" },
    { id: 34, question: "Играть в одиночку или в команде?", optionA: "Соло", optionB: "Команда", category: "games" },
    { id: 35, question: "Петь или танцевать?", optionA: "Петь 🎤", optionB: "Танцевать 💃", category: "other" },
    { id: 36, question: "Рисовать или фотографировать?", optionA: "Рисовать", optionB: "Фоткать", category: "other" },
    { id: 37, question: "Утро начинается с зарядки или с кофе?", optionA: "Зарядка", optionB: "Кофе", category: "food" },
    { id: 38, question: "Кемпинг или отель?", optionA: "Кемпинг ⛺", optionB: "Отель 🏨", category: "other" },
    { id: 39, question: "Быть директором или творцом?", optionA: "Директор", optionB: "Творец", category: "relationships" },
    { id: 40, question: "Иметь суперсилу или суперинтеллект?", optionA: "Сила", optionB: "Интеллект", category: "games" },
    { id: 41, question: "Жить в хрущёвке или в частном доме?", optionA: "Хрущёвка", optionB: "Дом", category: "other" },
    { id: 42, question: "Быть знаменитым или богатым?", optionA: "Знаменитым", optionB: "Богатым", category: "relationships" },
    { id: 43, question: "Путешествовать во времени или в пространстве?", optionA: "Время", optionB: "Пространство", category: "games" },
    { id: 44, question: "Смотреть аниме или читать мангу?", optionA: "Аниме", optionB: "Манга", category: "movies" },
    { id: 45, question: "Есть чтобы жить или жить чтобы есть?", optionA: "Есть чтобы жить", optionB: "Жить чтобы есть", category: "food" },
    { id: 46, question: "Быть пиратом или ниндзя?", optionA: "Пират 🏴‍☠️", optionB: "Ниндзя 🥷", category: "games" },
    { id: 47, question: "Смотреть ужасы или комедии?", optionA: "Ужасы 😱", optionB: "Комедии 😂", category: "movies" },
    { id: 48, question: "Жить без музыки или без книг?", optionA: "Без музыки", optionB: "Без книг", category: "other" },
    { id: 49, question: "Быстро ездить или долго гулять?", optionA: "Ездить 🏎️", optionB: "Гулять 🚶", category: "other" },
    { id: 50, question: "Иметь личного робота или волшебную палочку?", optionA: "Робот 🤖", optionB: "Палочка 🪄", category: "games" },
    { id: 51, question: "Спать 4 часа и всё успевать или 10 часов и ничего не делать?", optionA: "4 часа", optionB: "10 часов", category: "other" },
    { id: 52, question: "Быть космонавтом или аквалангистом?", optionA: "Космос 🚀", optionB: "Океан 🌊", category: "other" },
    { id: 53, question: "Вкусная еда без пользы или полезная без вкуса?", optionA: "Вкусная", optionB: "Полезная", category: "food" },
    { id: 54, question: "Жить в России или за границей?", optionA: "Россия 🇷🇺", optionB: "За границей 🌍", category: "other" },
    { id: 55, question: "Быть учителем или учеником?", optionA: "Учитель", optionB: "Ученик", category: "relationships" },
    { id: 56, question: "Играть в шахматы или в шашки?", optionA: "Шахматы ♟️", optionB: "Шашки 🔴", category: "games" },
    { id: 57, question: "Смотреть спорт или заниматься им?", optionA: "Смотреть", optionB: "Заниматься", category: "other" },
    { id: 58, question: "Жить один или с соседом?", optionA: "Один", optionB: "С соседом", category: "relationships" },
    { id: 59, question: "Иметь бесконечные деньги или бесконечное время?", optionA: "Деньги", optionB: "Время", category: "other" },
    { id: 60, question: "Быть вампиром или оборотнем?", optionA: "Вампир 🧛", optionB: "Оборотень 🐺", category: "games" },
    { id: 61, question: "Кино дома или в кинотеатре?", optionA: "Дома 🏠", optionB: "Кинотеатр 🎦", category: "movies" },
    { id: 62, question: "Мясо или овощи?", optionA: "Мясо 🥩", optionB: "Овощи 🥕", category: "food" },
    { id: 63, question: "Быть художником или музыкантом?", optionA: "Художник 🎨", optionB: "Музыкант 🎵", category: "other" },
    { id: 64, question: "Решать проблемы силой или умом?", optionA: "Силой", optionB: "Умом", category: "relationships" },
    { id: 65, question: "Жить в Средиземье или в Хогвартсе?", optionA: "Средиземье", optionB: "Хогвартс", category: "movies" },
    { id: 66, question: "Быть магом огня или воды?", optionA: "Огонь 🔥", optionB: "Вода 💧", category: "games" },
    { id: 67, question: "Слушать подкасты или музыку?", optionA: "Подкасты", optionB: "Музыка", category: "other" },
    { id: 68, question: "Жить без сна или без еды?", optionA: "Без сна", optionB: "Без еды", category: "other" },
    { id: 69, question: "Быть президентом или свободным художником?", optionA: "Президент", optionB: "Художник", category: "relationships" },
    { id: 70, question: "Иметь кота-телепата или собаку-телохранителя?", optionA: "Кот 🐱", optionB: "Собака 🐕", category: "games" },
    { id: 71, question: "Жить в Москве или в Питере?", optionA: "Москва", optionB: "Питер", category: "other" },
    { id: 72, question: "Быть актёром или режиссёром?", optionA: "Актёр", optionB: "Режиссёр", category: "movies" },
    { id: 73, question: "Шаурма или бургер?", optionA: "Шаурма", optionB: "Бургер 🍔", category: "food" },
    { id: 74, question: "Быть оптимистом или реалистом?", optionA: "Оптимист", optionB: "Реалист", category: "relationships" },
    { id: 75, question: "Путешествовать на поезде или на самолёте?", optionA: "Поезд 🚂", optionB: "Самолёт ✈️", category: "other" },
    { id: 76, question: "Иметь дракона или единорога?", optionA: "Дракон", optionB: "Единорог 🦄", category: "games" },
    { id: 77, question: "Смотреть Marvel или DC?", optionA: "Marvel", optionB: "DC", category: "movies" },
    { id: 78, question: "Готовить дома или заказывать еду?", optionA: "Готовить", optionB: "Заказывать", category: "food" },
    { id: 79, question: "Быть гением или счастливым?", optionA: "Гений", optionB: "Счастливый", category: "relationships" },
    { id: 80, question: "Жить в пустыне или в джунглях?", optionA: "Пустыня 🏜️", optionB: "Джунгли 🌴", category: "other" },
    { id: 81, question: "Уметь останавливать время или читать мысли?", optionA: "Время", optionB: "Мысли", category: "games" },
    { id: 82, question: "Фильм или сериал?", optionA: "Фильм", optionB: "Сериал", category: "movies" },
    { id: 83, question: "Сладкая жизнь или горькая правда?", optionA: "Сладкая жизнь", optionB: "Правда", category: "relationships" },
    { id: 84, question: "Быть великаном или гномом?", optionA: "Великан", optionB: "Гном", category: "games" },
    { id: 85, question: "Жить в СССР или в современной России?", optionA: "СССР", optionB: "Сейчас", category: "other" },
    { id: 86, question: "Пиво или вино?", optionA: "Пиво 🍺", optionB: "Вино 🍷", category: "food" },
    { id: 87, question: "Быть популярным в школе или незаметным гением?", optionA: "Популярным", optionB: "Гением", category: "relationships" },
    { id: 88, question: "Иметь реактивный ранец или подводную лодку?", optionA: "Ранец", optionB: "Лодка", category: "games" },
    { id: 89, question: "Смотреть фильм в 3D или в IMAX?", optionA: "3D", optionB: "IMAX", category: "movies" },
    { id: 90, question: "Есть только фастфуд или только ЗОЖ?", optionA: "Фастфуд", optionB: "ЗОЖ 🥗", category: "food" },
    { id: 91, question: "Быть кочевником или домоседом?", optionA: "Кочевник", optionB: "Домосед", category: "relationships" },
    { id: 92, question: "Управлять погодой или растениями?", optionA: "Погода", optionB: "Растения", category: "games" },
    { id: 93, question: "Жить на Марсе или на Земле?", optionA: "Марс", optionB: "Земля", category: "other" },
    { id: 94, question: "Быть учёным или изобретателем?", optionA: "Учёный", optionB: "Изобретатель", category: "other" },
    { id: 95, question: "Смотреть ТикТок или YouTube?", optionA: "ТикТок", optionB: "YouTube", category: "movies" },
    { id: 96, question: "Борщ или пельмени?", optionA: "Борщ 🍜", optionB: "Пельмени 🥟", category: "food" },
    { id: 97, question: "Быть загадочным или открытым?", optionA: "Загадочным", optionB: "Открытым", category: "relationships" },
    { id: 98, question: "Иметь меч-кладенец или лук со стрелами?", optionA: "Меч ⚔️", optionB: "Лук 🏹", category: "games" },
    { id: 99, question: "Жить вечно молодым или стареть мудро?", optionA: "Молодым", optionB: "Мудрым", category: "other" },
    { id: 100, question: "Любовь или деньги?", optionA: "Любовь ❤️", optionB: "Деньги 💰", category: "relationships" },
    { id: 101, question: "Быть тенью или светом?", optionA: "Тень", optionB: "Свет", category: "games" },
    { id: 102, question: "Иметь бесконечную память или бесконечную фантазию?", optionA: "Память", optionB: "Фантазия", category: "other" },
    { id: 103, question: "Друзья или семья?", optionA: "Друзья", optionB: "Семья", category: "relationships" },
    { id: 104, question: "Быть бессмертным или неуязвимым?", optionA: "Бессмертный", optionB: "Неуязвимый", category: "games" },
    { id: 105, question: "Смотреть аниме или западные мультфильмы?", optionA: "Аниме", optionB: "Западные", category: "movies" },
    { id: 106, question: "Шоколад или мороженое?", optionA: "Шоколад 🍫", optionB: "Мороженое 🍦", category: "food" },
    { id: 107, question: "Жить в замке или в космическом корабле?", optionA: "Замок 🏰", optionB: "Корабль 🚀", category: "games" },
    { id: 108, question: "Быть героем в тени или звездой на сцене?", optionA: "Герой в тени", optionB: "Звезда", category: "relationships" },
    { id: 109, question: "Война или мир?", optionA: "Мир ☮️", optionB: "Война ⚔️", category: "other" },
    { id: 110, question: "Иметь способность лечить или разрушать?", optionA: "Лечить 💉", optionB: "Разрушать 💥", category: "games" },
];